### ISSUE TITLE
Some feature requests

### ISSUE THREAD

**Issue by djch** [axiome-oss/django-initial-avatars#4] opened 2016-03-25 08:42 UTC
I've been playing around with this a bit today—really great little library!

I wanted to share a few things I'd love to see added:
1. Support for 2x screens e.g. the resolution of the generated .png being twice that of the `size` property.
2. The ability to set a fixed text colour; e.g. white or black. — I realise this could be tricky given how you're measuring contrast for this now.
3. The ability to set a "palette" of predefined background colours for the avatars to be chosen from randomly.
4. A way to tweak the font weight/style (if not the family).

Those are more or less in order of importance for me.

---

Again, awesome work so far :ok_hand:

**Comment by b0bbywan** [comment] 2016-03-29 14:30
Thanks for the feedback, it's much appreciated !

I agree those features can be useful, I have some questions on them before starting to code though
1. Would it be a True/False settings, or is there a way to detect the kind of screen from the request and serve the correct resolution ? I don't think so but it might be worth asking. Also do you know how it translates in Pillow ? 
2. A "use at your own risk" setting which might sometimes render unreadable avatars can be easily added, but doing it properly is indeed tricky, I don't know if it can be done. It can work nicely in addition of features 3 & 4 though.
3. A setting with a tuple of RGB colors chosen randomly ? The lib would have to store the chosen color for generation of new sizes, I was thinking of storing the color in a file in the user's folder on the backend as I'd like to avoid using a database. It would slow the generation of avatars however, so if you have a better solution I'll take it ! Maybe using a single json file would be quicker ?
4. It can be done quite easily by adding a setting to a class that extends the AvatarGenerator class. To use your own font, you would just need to rewrite the font method, maybe also the font_size and position ones if your font has a different size.

Thanks again for the feedback, I'll post the advancement on the develop branch. Let me know if you want to implement some of the features by yourself !

**Comment by djch** [comment] 2016-03-29 23:13
Hey @b0bbywan thanks for giving these some consideration so soon.

Full disclosure: I'm more of a designer than a programmer—I know my way around HTML & CSS, but not python so much. I work on Django-based products so I can get by dealing with simple stuff like settings and templates. That's why I like this library: it's easy for someone like me to drop in to a project.
1. I think you could achieve this just in the HTML using the [`srcset`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#Example_3_Using_the_srcset_attribute) attribute. Basically, you render each resolution of the PNG, and then add a `srcset` attribute for each one; `1x`, `2x` etc. The browser chooses the best one. It's not supported in IE11 on down, but is by just about every other browser.
2. Cool—the black lettering doesn't really work for me aesthetically. I'd rather deal with the contrast by managing the background colours carefully.
3. Yeah, I was imagining this as another Django setting which would accept a tuple of different hex values. I have no idea about the performance of that approach though.
4. This is, again, an aesthetic thing but I feel a lighter weight of the font would be more readable, especially once you're getting a nice sharp resolution on retina displays. I don't really have anything against the Ubuntu Sans family in general.

Thanks again, and sorry I'm not quite skilled enough with Python/Pillow etc. to submit pull requests of my own for this.

**Comment by b0bbywan** [comment] 2016-03-30 15:39
No problem, personnally I am nothing of a designer :)

I started to implement all features on the develop branch, you can test them if you want, here's what I did for now:
1. if 'AVATAR_HIGH_RESOLUTION' is set to True, the lib generates another avatar twice as large named like this (for instance): 80x80_circle@2x.png, which seems to be the standard naming for retina-ready images. From what I read [here](http://www.leemunroe.com/designing-for-high-resolution-retina-displays/) you can then use css or js (RetinaJS) to let the browser choose the appropriate version.
2. use 'AVATAR_DEFAUL_TEXT_COLOR' with 'white' or 'black' to force the text color.
3. use 'AVATAR_COLORS' to use  palette of predefined background colors, like this:

```
AVATAR_COLORS = (
    (124, 25, 56),
    (123, 27, 91),
    (156, 178, 56)
)
```
1. To change the font, create a custom AvatarGenerator in your project, for example:
   'my_project.avatar_backend.py':

```
from initial_avatars.generator import AvatarGenerator
from PIL import ImageFont
import os

class MyAvatarBackend(AvatarGenerator):

     def font(self):
        font_path = '/path/to/your/font'
        font_size = self.font_size()
        return ImageFont.truetype(font_path, size=font_size)

```

and define the following setting:
`AVATAR_GENERATOR_BACKEND = 'my_project.avatar_backend.MyAvatarBackend'`
I didn't really test the last one for now, so it may not work as expected

Let me know how it works for you !

**Comment by djch** [comment] 2016-03-31 05:06
Excellent, thanks @b0bbywan. I'll give these a shot when I get a chance, in the next few days.

**Comment by djch** [comment] 2016-04-04 06:12
Hey @b0bbywan — so my settings look like this now:

```
# Avatar config options
AVATAR_STORAGE_BACKEND = 'django.contrib.staticfiles.storage.StaticFilesStorage'
AVATAR_STORAGE_FOLDER = 'avatars'
AVATAR_DEFAULT_SHAPE = 'circle'
AVATAR_HIGH_RESOLUTION = 'True'
AVATAR_DEFAUL_TEXT_COLOR = 'white'
AVATAR_COLORS = (
    (37, 114, 221),
    (26, 193, 255),
    (47, 96, 125),
    (114, 83, 216),
    (105, 224, 58),
    (26, 286, 33),
    (242, 0, 99),
    (83, 83, 83),
    (254, 208, 33)
)
```

But I'm getting this error:
![screen shot 2016-04-04 at 4 04 35 pm](https://cloud.githubusercontent.com/assets/4392286/14239496/d6ab6656-fa7f-11e5-93d6-23ba6f9f0925.png)
(because the file doesn't exist)

Thinking I may I have missed something about the .json :smile:

**Comment by b0bbywan** [comment] 2016-04-04 11:50
My bad actually, I was writing the json file in the library folder, as it's a system folder only root can write in it. I always use virtualenvs so I didn't think of this. I moved it to the storage backend, it's should be ok now.

Also, I added the srcset in the img tag for feature 1 as you suggested.

**Comment by djch** [comment] 2016-04-05 01:25
Nice, thanks! 

It seems like the image assets aren't be generated now, so they 404. Not sure what the best way to go about debugging that is...

**Comment by b0bbywan** [comment] 2016-04-05 08:36
Well that's a shame. I tried your settings, and images were generated as expected so I'm not sure either. Have you checked in your STATIC_ROOT folder for the assets ? Is this about all assets or just 2x ? as it's designed, the app doesn't generate the 2x if the 1x already exists, so you have to delete all avatars to get both sizes regenerated.

**Comment by b0bbywan** [comment] 2016-04-05 08:40
Well that's a shame. I tried your settings, and images were generated as expected so I'm not sure either. Have you checked in your STATIC_ROOT folder for the assets ? Is this about all assets or just 2x ? As it's designed, the app doesn't generate the 2x if the 1x already exists, so you have to delete all avatars to get both sizes regenerated.

**Comment by djch** [comment] 2016-04-06 00:32
Yeah, it doesn't seem to generating any of the assets now. I just tried deleting the avatars/ folder from the STATIC_ROOT completely and it's not recreating it.

**Comment by djch** [comment] 2016-04-06 04:17
So I rolled back to v0.8.1 to make sure I'm not crazy, and that it _was_ working... but it actually isn't now. Same lack of assets being generated.

So it's nothing to do with the new code, I'm just missing something and I'm not sure what.

**Comment by djch** [comment] 2016-04-06 05:12
Alright, I ditched the `AVATAR_STORAGE_BACKEND` setting, which got the avatars/ directory generated again. At that point I got another error about user_colors.json (except in the STATIC_ROOT/avatars/ folder this time). I `touch`ed that file, made sure the permissions were okay and have now ended up on:

```
Exception Type: AttributeError at /dashboard/admin/
Exception Value: 'StringIO' object has no attribute 'chunks'
```

:point_up_2: That exception doesn't happen on v0.8.1, _but_ I need that `AVATAR_STORAGE_BACKEND` setting otherwise the `src` paths come up wrong (that's mostly the fault of a project's unusual approach to static files

**Comment by b0bbywan** [comment] 2016-04-06 15:44
I'm sorry but I can't reproduce it so I don't have any clue about how to help you. I launched my unit test with those settings and didn't get any errors.

```
from __future__ import unicode_literals
import os

SECRET_KEY = 'fake-key'
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'TEST_NAME': os.path.join(os.path.dirname(__file__), 'django_initial_avatars.sqlite'),
    }
}
INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'initial_avatars',
    'django_gravatar',
]
MEDIA_URL = 'http://django-initial-avatars.py/'
STATIC_URL = 'static/'
STATIC_ROOT = 'tests/static_root'
MEDIA_ROOT = 'tests/static'
ROOT_URLCONF = 'initial_avatars.urls'
AVATAR_STORAGE_BACKEND = 'django.contrib.staticfiles.storage.StaticFilesStorage'
AVATAR_STORAGE_FOLDER = 'avatars'
AVATAR_HIGH_RESOLUTION = True
AVATAR_DEFAUL_TEXT_COLOR = 'white'
AVATAR_COLORS = (
    (37, 114, 221),
    (26, 193, 255),
    (47, 96, 125),
    (114, 83, 216),
    (105, 224, 58),
    (26, 286, 33),
    (242, 0, 99),
    (83, 83, 83),
    (254, 208, 33)
)
```

 I'm gonna publish another branch to try with a database instead of a json file, maybe it'll be better. The json file doesn't seem a good idea anyway

**Comment by djch** [comment] 2016-04-06 23:47
No worries. I probably should have mentioned this earlier but the project I'm trying to get this running on is using Django 1.4 and Python 2.6 (both currently unsupported I know).

I'll figure it out somehow.

**Closed as completed** 2016-09-10 17:32 UTC
